services:
  postgresContainer:
    image: postgres:13
    container_name: heatExGA-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-shared-network
      
  heatexga-api:
    container_name: heatexga-api
    build:
      context: .
    ports:
      - "8100:8100"
    volumes:
      - ./djangoapp:/djangoapp
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
      - ./.env:/.env
    
    env_file:
      - ./.env
    
    networks:
      - my-shared-network
    
    depends_on:
      - postgresContainer
  


networks:
  my-shared-network:
    external: true
