# Generated by Django 5.1.1 on 2024-10-23 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeltaSB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dn_min_meters', models.FloatField(unique=True)),
                ('Dn_max_meters', models.FloatField(unique=True)),
                ('Dn_min_inch', models.FloatField(unique=True)),
                ('Dn_max_inch', models.FloatField(unique=True)),
                ('DeltaSB_meters', models.FloatField()),
                ('DeltaSB_inch', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('angle', models.FloatField()),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='LiLo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure_class_pascal', models.FloatField()),
                ('pressure_class_psi', models.FloatField()),
                ('li_meters', models.FloatField()),
                ('lo_meters', models.FloatField()),
                ('li_inch', models.FloatField()),
                ('lo_inch', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NozzleDiameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dc_min_meters', models.FloatField(unique=True)),
                ('Dc_max_meters', models.FloatField(unique=True)),
                ('Dc_min_inch', models.FloatField(unique=True)),
                ('Dc_max_inch', models.FloatField(unique=True)),
                ('nozzle_diameter_meters', models.FloatField()),
                ('nozzle_diameter_inch', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TubeDiameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter_meters', models.FloatField()),
                ('diameter_inch', models.FloatField()),
                ('intern_diameter_meters', models.FloatField(null=True)),
                ('intern_diameter_inch', models.FloatField(null=True)),
                ('tube_thickness', models.FloatField(null=True)),
                ('description', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConstantsB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reynolds_min', models.FloatField()),
                ('reynolds_max', models.FloatField()),
                ('b1', models.FloatField()),
                ('b2', models.FloatField()),
                ('b3', models.FloatField()),
                ('b4', models.FloatField()),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.layout')),
            ],
        ),
        migrations.CreateModel(
            name='ConstantsA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reynolds_min', models.FloatField()),
                ('reynolds_max', models.FloatField()),
                ('a1', models.FloatField()),
                ('a2', models.FloatField()),
                ('a3', models.FloatField()),
                ('a4', models.FloatField()),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.layout')),
            ],
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_meters', models.FloatField()),
                ('pitch_inch', models.FloatField()),
                ('pp_meters', models.FloatField()),
                ('pp_inch', models.FloatField()),
                ('pn_meters', models.FloatField()),
                ('pn_inch', models.FloatField()),
                ('description', models.CharField(max_length=256, null=True)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.layout')),
                ('de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.tubediameter')),
            ],
        ),
        migrations.CreateModel(
            name='TubeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ds_meters', models.FloatField()),
                ('Ds_inch', models.FloatField()),
                ('Dotl_meters', models.FloatField()),
                ('Dotl_inch', models.FloatField()),
                ('n1', models.PositiveIntegerField(blank=True, null=True)),
                ('n2', models.PositiveIntegerField(blank=True, null=True)),
                ('n4', models.PositiveIntegerField(blank=True, null=True)),
                ('n6', models.PositiveIntegerField(blank=True, null=True)),
                ('n8', models.PositiveIntegerField(blank=True, null=True)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.layout')),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.pitch')),
                ('de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.tubediameter')),
            ],
        ),
        migrations.CreateModel(
            name='InputsShellAndTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T1_hot', models.FloatField()),
                ('T2_hot', models.FloatField()),
                ('t1_cold', models.FloatField()),
                ('t2_cold', models.FloatField()),
                ('wf', models.FloatField()),
                ('wq', models.FloatField()),
                ('cp_quente', models.FloatField()),
                ('cp_frio', models.FloatField()),
                ('casco_passagens', models.IntegerField()),
                ('rho_q', models.FloatField()),
                ('rho_f', models.FloatField()),
                ('mi_f', models.FloatField()),
                ('mi_q', models.FloatField()),
                ('k_q', models.FloatField()),
                ('k_f', models.FloatField()),
                ('tipo_q', models.CharField(max_length=256)),
                ('tipo_f', models.CharField(max_length=256)),
                ('Rd_f', models.FloatField()),
                ('Rd_q', models.FloatField()),
                ('n', models.IntegerField(choices=[(1, 'Uma Passagem nos tubos'), (2, 'Duas Passagem nos tubos'), (4, 'Quatro Passagem nos tubos'), (6, 'Seis Passagem nos tubos'), (8, 'Oito Passagem nos tubos')], help_text='Número de passagens nos tubos', null=True)),
                ('de', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.tubediameter')),
            ],
        ),
    ]
