# Generated by Django 5.1.1 on 2024-10-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='description',
            field=models.CharField(),
        ),
    ]
