# Generated by Django 5.1.1 on 2024-10-27 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputsshellandtube',
            name='pith',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.pitch'),
        ),
    ]
