# Generated by Django 5.1.1 on 2024-10-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_inputsshellandtube_pith'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='Rd_f',
            field=models.FloatField(default=0.002),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='Rd_q',
            field=models.FloatField(default=0.001),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='T1_hot',
            field=models.FloatField(default=219),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='T2_hot',
            field=models.FloatField(default=100.4),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='casco_passagens',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='cp_frio',
            field=models.FloatField(default=0.998),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='cp_quente',
            field=models.FloatField(default=0.52),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='k_f',
            field=models.FloatField(default=0.336),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='k_q',
            field=models.FloatField(default=0.0699),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='mi_f',
            field=models.FloatField(default=0.7),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='mi_q',
            field=models.FloatField(default=0.375),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='rho_f',
            field=models.FloatField(default=62.2427),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='rho_q',
            field=models.FloatField(default=46.8537),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='t1_cold',
            field=models.FloatField(default=86),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='t2_cold',
            field=models.FloatField(default=100.4),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='wf',
            field=models.FloatField(default=59.95),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='wq',
            field=models.FloatField(default=110687),
        ),
    ]
