# Generated by Django 5.1.1 on 2024-10-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_tubediameter_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constantsa',
            name='reynolds_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='constantsa',
            name='reynolds_min',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='constantsb',
            name='reynolds_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='constantsb',
            name='reynolds_min',
            field=models.FloatField(),
        ),
    ]
