# Generated by Django 5.1.1 on 2024-10-27 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_inputsshellandtube_rd_f_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputsshellandtube',
            old_name='pith',
            new_name='pitch',
        ),
    ]
