# Generated by Django 5.1.1 on 2024-10-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_rename_pith_inputsshellandtube_pitch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='Rd_f',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='Rd_q',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='T1_hot',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='T2_hot',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='casco_passagens',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='cp_frio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='cp_quente',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='k_f',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='k_q',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='mi_f',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='mi_q',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='rho_f',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='rho_q',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='t1_cold',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='t2_cold',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='wf',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='wq',
            field=models.FloatField(),
        ),
    ]
