# Generated by Django 5.1.1 on 2024-10-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_constantsa_reynolds_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='description',
            field=models.CharField(null=True),
        ),
    ]
