# Generated by Django 5.1.1 on 2024-10-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_pitch_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputsShellAndTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T1', models.FloatField()),
                ('T2', models.FloatField()),
                ('t1', models.FloatField()),
                ('t2', models.FloatField()),
                ('wf', models.FloatField()),
                ('wq', models.FloatField()),
                ('cp_quente', models.FloatField()),
                ('cp_frio', models.FloatField()),
                ('casco_passagens', models.IntegerField()),
                ('rho_q', models.FloatField()),
                ('rho_f', models.FloatField()),
                ('mi_f', models.FloatField()),
                ('mi_q', models.FloatField()),
                ('k_q', models.FloatField()),
                ('k_f', models.FloatField()),
                ('tipo_q', models.CharField()),
                ('tipo_f', models.CharField()),
                ('Rd_f', models.FloatField()),
                ('Rd_q', models.FloatField()),
            ],
        ),
    ]
