# Generated by Django 5.1.1 on 2024-10-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_inputsshellandtube_rd_f_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputsshellandtube',
            name='reference',
            field=models.TextField(default=''),
        ),
    ]
