# Generated by Django 5.1.1 on 2024-10-30 00:38

import API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_inputsshellandtube_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputsshellandtube',
            name='Ds_inch',
            field=models.FloatField(choices=API.models.InputsShellAndTube.get_ds_inch_choices, null=True),
        ),
    ]
