# Generated by Django 5.1.1 on 2024-10-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_inputsshellandtube_l'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputsshellandtube',
            name='shell_fluid',
            field=models.CharField(choices=[('hot', 'hot'), ('cold', 'cold')], max_length=4, null=True),
        ),
    ]
