# Generated by Django 5.1.1 on 2024-10-30 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_inputsshellandtube_shell_fluid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tubediameter',
            name='intern_diameter_inch',
        ),
        migrations.RemoveField(
            model_name='tubediameter',
            name='intern_diameter_meters',
        ),
        migrations.CreateModel(
            name='TubeInternDiameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intern_diameter_meters', models.FloatField(null=True)),
                ('intern_diameter_inch', models.FloatField(null=True)),
                ('standard', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=256, null=True)),
                ('tube_diameter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.tubediameter')),
            ],
        ),
    ]
