# Generated by Django 5.1.1 on 2024-10-30 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_remove_tubediameter_intern_diameter_inch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputsshellandtube',
            name='de',
        ),
        migrations.RemoveField(
            model_name='tubediameter',
            name='tube_thickness',
        ),
        migrations.AddField(
            model_name='inputsshellandtube',
            name='di',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.tubeinterndiameter'),
        ),
        migrations.AddField(
            model_name='tubeinterndiameter',
            name='tube_thickness',
            field=models.FloatField(null=True),
        ),
    ]
