# Generated by Django 5.1.1 on 2024-10-30 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_remove_inputsshellandtube_de_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tubeinterndiameter',
            old_name='tube_thickness',
            new_name='tube_thickness_incb',
        ),
    ]
