# Generated by Django 5.1.1 on 2024-10-30 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_rename_tube_thickness_tubeinterndiameter_tube_thickness_incb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tubeinterndiameter',
            old_name='tube_thickness_incb',
            new_name='tube_thickness_inch',
        ),
    ]
