# Generated by Django 5.1.1 on 2024-10-30 23:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_inputsshellandtube_ls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='ls',
            field=models.DecimalField(decimal_places=3, help_text='Espaçamento entre defletores em funçao do comprimento (L) do trocador (%)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
