# Generated by Django 5.1.1 on 2024-10-30 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_alter_inputsshellandtube_ls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputsshellandtube',
            old_name='ls',
            new_name='ls_percent',
        ),
    ]
