# Generated by Django 5.1.1 on 2024-10-31 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_inputsshellandtube_tube_materials_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TubeMaterials',
            new_name='TubeMaterial',
        ),
        migrations.RenameField(
            model_name='inputsshellandtube',
            old_name='tube_materials',
            new_name='tube_material',
        ),
    ]
