# Generated by Django 5.1.1 on 2024-11-01 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_rename_tubematerials_tubematerial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputsshellandtube',
            name='lc_percent',
            field=models.DecimalField(decimal_places=3, help_text='Corte defeltor em funçao do comprimento do diâmetro  (L) do trocador (%)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.15), django.core.validators.MaxValueValidator(0.4)]),
        ),
    ]
