# Generated by Django 5.1.1 on 2024-11-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_inputsshellandtube_lc_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputsshellandtube',
            name='shell_thickness_meters',
            field=models.FloatField(null=True),
        ),
    ]
