# Generated by Django 5.1.1 on 2024-11-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_inputsshellandtube_shell_thickness_meters'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputsshellandtube',
            name='pression_class',
            field=models.FloatField(choices=[(150.0, '150 psi'), (600.0, '600 psi')], null=True),
        ),
        migrations.AddField(
            model_name='lilo',
            name='Dc_inch',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lilo',
            name='Dc_meters',
            field=models.FloatField(null=True),
        ),
    ]
