# Generated by Django 5.1.1 on 2024-11-01 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0022_inputsshellandtube_pression_class_lilo_dc_inch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputsshellandtube',
            old_name='pression_class',
            new_name='pressure_class',
        ),
    ]
