# Generated by Django 5.1.1 on 2024-11-02 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0024_alter_layout_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='ls_percent',
            field=models.DecimalField(decimal_places=3, help_text='Espaçamento entre defletores em funçao do diametro interno do trocador (Ds) (%)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
