# Generated by Django 5.1.1 on 2024-11-09 19:27

import API.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0025_alter_inputsshellandtube_ls_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputsshellandtube',
            name='calculation_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='Ds_inch',
            field=models.FloatField(blank=True, choices=API.models.InputsShellAndTube.get_ds_inch_choices, null=True),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='L',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='casco_passagens',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='di',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.tubeinterndiameter'),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='lc_percent',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Corte defeltor em funçao do comprimento do diâmetro  (L) do trocador (%)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1499999999999999944488848768742172978818416595458984375')), django.core.validators.MaxValueValidator(Decimal('0.40000000000000002220446049250313080847263336181640625'))]),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='ls_percent',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Espaçamento entre defletores em funçao do diametro interno do trocador (Ds) (%)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))]),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='n',
            field=models.IntegerField(blank=True, choices=[(1, 'Uma Passagem nos tubos'), (2, 'Duas Passagem nos tubos'), (4, 'Quatro Passagem nos tubos'), (6, 'Seis Passagem nos tubos'), (8, 'Oito Passagem nos tubos')], help_text='Número de passagens nos tubos', null=True),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='pitch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.pitch'),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='pressure_class',
            field=models.FloatField(blank=True, choices=[(150.0, '150 psi'), (600.0, '600 psi')], null=True),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='reference',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='shell_fluid',
            field=models.CharField(blank=True, choices=[('hot', 'hot'), ('cold', 'cold')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='shell_thickness_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='tube_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.tubematerial'),
        ),
    ]
