# Generated by Django 5.1.1 on 2024-12-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0030_inputsshellandtube_perda_carga_admissivel_casco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='perda_carga_admissivel_casco',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='perda_carga_admissivel_tubo',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
