# Generated by Django 5.1.1 on 2024-12-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0033_results_constraint_ea_max_results_constraint_ea_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Charts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_id', models.UUIDField(blank=True, null=True)),
                ('files', models.ManyToManyField(to='API.file')),
            ],
        ),
    ]
