# Generated by Django 5.1.1 on 2024-12-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0035_results_res'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputsshellandtube',
            name='n',
            field=models.IntegerField(blank=True, choices=[(1, 'Uma Passagem nos tubos'), (2, 'Duas Passagens nos tubos'), (4, 'Quatro Passagens nos tubos'), (6, 'Seis Passagens nos tubos'), (8, 'Oito Passagens nos tubos')], help_text='Número de passagens nos tubos', null=True),
        ),
    ]
