# Generated by Django 5.1.1 on 2024-12-14 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0036_alter_inputsshellandtube_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='charts',
            name='csv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_csv', to='API.file'),
        ),
    ]
