version: '3'
services:      
  sthega:
    container_name: sthega
    restart: always
    build:
      context: .
    expose:
      - "8000"
    volumes:
      - .:/djangoapp
      - ./static:/static/
      - ./media:/media/
      - .env:/.env
    
    env_file:
      - .env
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./media:/media
    depends_on:
      - sthega
  
