version: '3'
services:      
  sthega:
    container_name: sthega
    restart: always
    build:
      context: .
    expose:
      - "8000"
    volumes:
      - .:/djangoapp
      - ./static:/static/
      - ./media:/media/
      - .env:/.env
    env_file:
      - .env
    depends_on:
      - sthega_db

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./media:/media
    depends_on:
      - sthega
  
  sthega_db:
    image: postgres:16.7
    container_name: sthega_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: sthega_db
    volumes:
      - ${PG_DATA}:/var/lib/postgresql/data 
volumes:
  PG_DATA:  # Aqui você define o volume nomeado


  
