"""upgrade

Revision ID: 04e49d5d18ff
Revises: 
Create Date: 2024-04-16 23:03:44.814131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04e49d5d18ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliation_design_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seila2', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliation_termo_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_avaliation', sa.String(length=30), nullable=False),
    sa.Column('T1', sa.Float(), nullable=False),
    sa.Column('T2', sa.Float(), nullable=False),
    sa.Column('mi_q', sa.Float(), nullable=False),
    sa.Column('cp_quente', sa.Float(), nullable=False),
    sa.Column('Rd_q', sa.Float(), nullable=False),
    sa.Column('k_q', sa.Float(), nullable=False),
    sa.Column('rho_q', sa.Float(), nullable=False),
    sa.Column('w_q', sa.Float(), nullable=False),
    sa.Column('tipo_q', sa.String(length=30), nullable=False),
    sa.Column('fluid_side', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliation_termo_inputs_cold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('t1', sa.Float(), nullable=False),
    sa.Column('t2', sa.Float(), nullable=False),
    sa.Column('mi_f', sa.Float(), nullable=False),
    sa.Column('cp_frio', sa.Float(), nullable=False),
    sa.Column('Rd_f', sa.Float(), nullable=False),
    sa.Column('k_f', sa.Float(), nullable=False),
    sa.Column('rho_f', sa.Float(), nullable=False),
    sa.Column('w_f', sa.Float(), nullable=False),
    sa.Column('tipo_f', sa.String(length=30), nullable=False),
    sa.Column('fluid_side', sa.String(length=30), nullable=False),
    sa.Column('seila', sa.String(length=30), nullable=False),
    sa.Column('seila2', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaliation_termo_inputs_cold')
    op.drop_table('avaliation_termo_inputs')
    op.drop_table('avaliation_results')
    op.drop_table('avaliation_design_inputs')
    # ### end Alembic commands ###
