"""upgrade

Revision ID: 1348f9f12bfa
Revises: 2a3282b602ac
Create Date: 2024-05-11 16:46:32.393235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1348f9f12bfa'
down_revision: Union[str, None] = '2a3282b602ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('li_lo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pressure_class', sa.Float(), nullable=False),
    sa.Column('pressure_class_psi', sa.Float(), nullable=False),
    sa.Column('Dc', sa.Float(), nullable=False),
    sa.Column('Dc_inch', sa.Float(), nullable=False),
    sa.Column('li', sa.Float(), nullable=False),
    sa.Column('li_inch', sa.Float(), nullable=False),
    sa.Column('lo', sa.Float(), nullable=False),
    sa.Column('lo_inch', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('li_lo')
    # ### end Alembic commands ###
