"""upgrade

Revision ID: 298e9242d64b
Revises: b23a9fa5e2f4
Create Date: 2024-04-17 17:01:48.370713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '298e9242d64b'
down_revision: Union[str, None] = 'b23a9fa5e2f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('avaliation_design_inputs', 'seila2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avaliation_design_inputs', sa.Column('seila2', sa.VARCHAR(length=30), nullable=False))
    # ### end Alembic commands ###
