"""upgrade

Revision ID: 2a3282b602ac
Revises: d8d30504c305
Create Date: 2024-05-11 16:17:16.256232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a3282b602ac'
down_revision: Union[str, None] = 'd8d30504c305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nozzle_diameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Dc_max', sa.Float(), nullable=False),
    sa.Column('Dc_max_inch', sa.Float(), nullable=False),
    sa.Column('Dc_min', sa.Float(), nullable=False),
    sa.Column('Dc_min_inch', sa.Float(), nullable=False),
    sa.Column('d_nozzle', sa.Float(), nullable=False),
    sa.Column('d_nozzle_inch', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nozzle_diameter')
    # ### end Alembic commands ###
