"""upgrade

Revision ID: 33ca2bf8df2f
Revises: 
Create Date: 2024-05-11 13:22:10.667296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33ca2bf8df2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliation_thermo_input',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_avaliation', sa.String(length=30), nullable=False),
    sa.Column('T1', sa.Float(), nullable=False),
    sa.Column('T2', sa.Float(), nullable=False),
    sa.Column('mi_q', sa.Float(), nullable=False),
    sa.Column('cp_quente', sa.Float(), nullable=False),
    sa.Column('Rd_q', sa.Float(), nullable=False),
    sa.Column('k_q', sa.Float(), nullable=False),
    sa.Column('rho_q', sa.Float(), nullable=False),
    sa.Column('w_q', sa.Float(), nullable=False),
    sa.Column('tipo_q', sa.String(length=30), nullable=False),
    sa.Column('fluid_side', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('constants_for_ab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layout', sa.Enum('TRIANGULAR', 'ROTATED_TRIANGULAR', 'SQUARE', 'ROTATED_SQUARE', name='tubelayout'), nullable=False),
    sa.Column('Re', sa.Float(), nullable=False),
    sa.Column('a1', sa.Float(), nullable=False),
    sa.Column('a2', sa.Float(), nullable=False),
    sa.Column('a3', sa.Float(), nullable=False),
    sa.Column('a4', sa.Float(), nullable=False),
    sa.Column('b1', sa.Float(), nullable=False),
    sa.Column('b2', sa.Float(), nullable=False),
    sa.Column('b3', sa.Float(), nullable=False),
    sa.Column('b4', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tube_count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Ds', sa.Float(), nullable=False),
    sa.Column('Ds_inch', sa.Float(), nullable=False),
    sa.Column('Dotl', sa.Float(), nullable=False),
    sa.Column('Dotl_inch', sa.Float(), nullable=False),
    sa.Column('de', sa.Float(), nullable=False),
    sa.Column('de_inch', sa.Float(), nullable=False),
    sa.Column('pitch', sa.Float(), nullable=False),
    sa.Column('pitch_inch', sa.Float(), nullable=False),
    sa.Column('layout', sa.Enum('TRIANGULAR', 'ROTATED_TRIANGULAR', 'SQUARE', 'ROTATED_SQUARE', name='tubelayout'), nullable=False),
    sa.Column('n1', sa.Integer(), nullable=False),
    sa.Column('n2', sa.Integer(), nullable=False),
    sa.Column('n4', sa.Integer(), nullable=False),
    sa.Column('n6', sa.Integer(), nullable=False),
    sa.Column('n8', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliation_design_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thermo_inputs_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['thermo_inputs_id'], ['avaliation_thermo_input.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thermo_inputs_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['thermo_inputs_id'], ['avaliation_thermo_input.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliation_thermo_inputs_cold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('t1', sa.Float(), nullable=False),
    sa.Column('t2', sa.Float(), nullable=False),
    sa.Column('mi_f', sa.Float(), nullable=False),
    sa.Column('cp_frio', sa.Float(), nullable=False),
    sa.Column('Rd_f', sa.Float(), nullable=False),
    sa.Column('k_f', sa.Float(), nullable=False),
    sa.Column('rho_f', sa.Float(), nullable=False),
    sa.Column('w_f', sa.Float(), nullable=False),
    sa.Column('tipo_f', sa.String(length=30), nullable=False),
    sa.Column('fluid_side', sa.String(length=30), nullable=False),
    sa.Column('thermo_inputs_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['thermo_inputs_id'], ['avaliation_thermo_input.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avaliation_thermo_inputs_cold')
    op.drop_table('avaliation_results')
    op.drop_table('avaliation_design_inputs')
    op.drop_table('tube_count')
    op.drop_table('constants_for_ab')
    op.drop_table('avaliation_thermo_input')
    # ### end Alembic commands ###
