"""upgrade

Revision ID: 8e1c40eef18d
Revises: 1348f9f12bfa
Create Date: 2024-05-11 17:02:59.212537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1c40eef18d'
down_revision: Union[str, None] = '1348f9f12bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('de', sa.Float(), nullable=False),
    sa.Column('de_inch', sa.Float(), nullable=False),
    sa.Column('pitch', sa.Float(), nullable=False),
    sa.Column('pitch_inch', sa.Float(), nullable=False),
    sa.Column('layout', sa.Enum('TRIANGULAR', 'ROTATED_TRIANGULAR', 'SQUARE', 'ROTATED_SQUARE', name='tubelayout'), nullable=False),
    sa.Column('pp', sa.Float(), nullable=False),
    sa.Column('pp_inch', sa.Float(), nullable=False),
    sa.Column('pn', sa.Float(), nullable=False),
    sa.Column('pn_inch', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pitch')
    # ### end Alembic commands ###
