"""upgrade

Revision ID: eaebce593cd1
Revises: e10deac0ddd3
Create Date: 2024-05-04 21:20:57.113573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaebce593cd1'
down_revision: Union[str, None] = 'e10deac0ddd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constants_for_ab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layout', sa.Enum('TRIANGULAR', 'ROTATED_TRIANGULAR', 'SQUARE', 'ROTATED_SQUARE', name='tubelayout'), nullable=False),
    sa.Column('Re', sa.Float(), nullable=False),
    sa.Column('a1', sa.Float(), nullable=False),
    sa.Column('a2', sa.Float(), nullable=False),
    sa.Column('a3', sa.Float(), nullable=False),
    sa.Column('a4', sa.Float(), nullable=False),
    sa.Column('b1', sa.Float(), nullable=False),
    sa.Column('b2', sa.Float(), nullable=False),
    sa.Column('b3', sa.Float(), nullable=False),
    sa.Column('b4', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('constants_for_ab')
    # ### end Alembic commands ###
